# Generated by Django 3.0.5 on 2024-05-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
